///////////////////////////////////////////////////////////
//  ExcelColumn.cs
//  Implementation of the Class ExcelColumn
//  Generated by Enterprise Architect
//  Created on:      21-5~{TB~}-2020 14:59:32
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Excel.Checker {
	public class ExcelColumn {



		public ExcelColumn(){

		}

		public int ColumnIndex{
			get;  set;
		}

		public string ColumnName{
			get;  set;
		}

	}//end ExcelColumn

}//end namespace FD.Excel.Checker