///////////////////////////////////////////////////////////
//  ExcelSheet.cs
//  Implementation of the Class ExcelSheet
//  Generated by Enterprise Architect
//  Created on:      21-5~{TB~}-2020 15:47:02
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;



using FD.Excel.Checker;
namespace FD.Excel.Checker {
	public class ExcelSheet {

		public ExcelSheet(){

			Columns = new List<ExcelColumn>();
		}

		public int ColumnNum{
			get
			            {
			                return Columns?.Count() ?? 0;
			            }
		}

		public IList<ExcelColumn> Columns{
			get;  set;
		}

		public int SheetIndex{
			get;  set;
		}

		public string SheetName{
			get;  set;
		}

		/// 
		/// <param name="index"></param>
		public ExcelColumn this[int index]{
			get{return Columns?[index];}
		}

		/// 
		/// <param name="name"></param>
		public ExcelColumn this[string name]{
			get{return Columns?.FirstOrDefault(f => name.Equals(f.ColumnName));}
		}

	}//end ExcelSheet

}//end namespace FD.Excel.Checker