///////////////////////////////////////////////////////////
//  ExcelStructure.cs
//  Implementation of the Class ExcelStructure
//  Generated by Enterprise Architect
//  Created on:      21-5~{TB~}-2020 16:28:20
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;



using FD.Excel.Checker;
namespace FD.Excel.Checker {
	public class ExcelStructure {

		public ExcelStructure(){

			Sheets = new List<ExcelSheet>();
		}

		/// 
		/// <param name="sheetName"></param>
		public bool Contains(string sheetName){

			return Sheets?.Any(s => s.SheetName == sheetName) ?? false;
		}

		public string Name{
			get;  set;
		}

		public int SheetNum{
			get
			            {
			                return Sheets?.Count() ?? 0;
			            }
		}

		public IList<ExcelSheet> Sheets{
			get;  set;
		}

		/// 
		/// <param name="index"></param>
		public ExcelSheet this[int index]{
			get{return Sheets?[index];}
		}

		/// 
		/// <param name="name"></param>
		public ExcelSheet this[string name]{
			get{return Sheets?.FirstOrDefault(f => name.Equals(f.SheetName));}
		}

	}//end ExcelStructure

}//end namespace FD.Excel.Checker