///////////////////////////////////////////////////////////
//  DataType.cs
//  Implementation of the Enumeration DataType
//  Generated by Enterprise Architect
//  Created on:      21-5ÔÂ-2020 14:59:32
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Excel.Checker {
	public enum DataType : int {

	}//end DataType

}//end namespace FD.Excel.Checker