///////////////////////////////////////////////////////////
//  TemplateRule.cs
//  Implementation of the Class TemplateRule
//  Generated by Enterprise Architect
//  Created on:      21-5~{TB~}-2020 16:54:54
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;



using FD.Excel.Checker;
namespace FD.Excel.Checker {
	public class TemplateRule {

		public TemplateRule(){

			this.SheetRules = new List<SheetRule>();
		}

		public int SheetNum{
			get
						            {
						                return SheetRules?.Count() ?? 0;
						            }
		}

		public IList<SheetRule> SheetRules{
			get;  set;
		}

		public string TemplateName{
			get;  set;
		}

		/// 
		/// <param name="sheetName"></param>
		public SheetRule this[string sheetName]{
			get{return SheetRules?.FirstOrDefault(f => sheetName.Equals(f.SheetName));}
		}

	}//end TemplateRule

}//end namespace FD.Excel.Checker