///////////////////////////////////////////////////////////
//  CheckErrorType.cs
//  Implementation of the Enumeration CheckErrorType
//  Generated by Enterprise Architect
//  Created on:      21-5ÔÂ-2020 14:59:32
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Excel.Checker {
	public enum CheckErrorType : int {

		ExcelRead,
		ExcelStructure,
		TemplateMatch,
		PKCheck,
		FKCheck,
		ColumnCheck

	}//end CheckErrorType

}//end namespace FD.Excel.Checker